//
//  CampusMapViewController.swift
//  MackTIA
//
//  Created by Joaquim Pessoa Filho on 19/08/16.
//  Copyright (c) 2016 Mackenzie. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import MapKit



class CampusMapViewController: UIViewController {
    @IBOutlet weak var mapView: MKMapView!
    let locationManager = CLLocationManager()
    
    // MARK: Object lifecycle
    
    override func awakeFromNib() {
        super.awakeFromNib()
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.locationManager.desiredAccuracy = kCLLocationAccuracyBest
        let authstate = CLLocationManager.authorizationStatus()
        if(authstate == CLAuthorizationStatus.NotDetermined){
            print("Not Authorised")
            locationManager.requestWhenInUseAuthorization()
        }
        
        loadPinAnnotations()
    }
    
    // MARK: Event handling
    
    func loadPinAnnotations() {
        
        let filePath = NSBundle.mainBundle().pathForResource("CampusMap", ofType: "plist")
        let properties = NSArray(contentsOfFile: filePath!)
        
        // Set MapView Region
        // -23.546954, -46.651796
        let centerCoordinate = CLLocationCoordinate2D(latitude: CLLocationDegrees(-23.546954), longitude: CLLocationDegrees(-46.651796))
        let region = MKCoordinateRegionMakeWithDistance(centerCoordinate, 600, 600)
        mapView.setRegion(region, animated: false)
        
        // Add Map Annotation
        for item in properties! {
            if let newPinData = item as? Dictionary<String,String>{
                let point = CGPointFromString(newPinData["location"]!)
                let coordinate = CLLocationCoordinate2D(latitude: CLLocationDegrees(point.x), longitude: CLLocationDegrees(point.y))
                
                let annotation = CampusMapAnnotation(name: newPinData["name"]!, buildName: newPinData["buildName"]!, number: newPinData["number"]!, coordinate: coordinate)
                mapView.addAnnotation(annotation)
            }
        }
    }
}

// MARK: - Map View delegate

extension CampusMapViewController: MKMapViewDelegate {
    func mapView(mapView: MKMapView, viewForAnnotation annotation: MKAnnotation) -> MKAnnotationView? {
        
        guard let annotation = annotation as? CampusMapAnnotation else {
            print(#function, "Problem with CampusMapAnnotation NIB")
            return nil
        }
        
        let view = self.mapView.dequeueReusableAnnotationViewWithIdentifier("CampusMap") ?? MKAnnotationView(annotation: annotation, reuseIdentifier: "CampusMap")
        
        let image = UIImage(named: "pin\(annotation.number)") ?? UIImage(named: "pinDefault")
        view.image = image
        view.enabled = true
        view.canShowCallout = true
        
        return view
    }
}
