//
//  CampusMapViewController.swift
//  MackTIA
//
//  Created by Joaquim Pessoa Filho on 19/08/16.
//  Copyright (c) 2016 Mackenzie. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import MapKit
import Polyline



class CampusMapViewController: UIViewController {
    @IBOutlet weak var mapView: MKMapView!
    let locationManager = CLLocationManager()
    var locValue: CLLocationCoordinate2D?
    
    // MARK: Object lifecycle
    
    override func awakeFromNib() {
        super.awakeFromNib()
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.locationManager.desiredAccuracy = kCLLocationAccuracyBest
        let authstate = CLLocationManager.authorizationStatus()
        if(authstate == CLAuthorizationStatus.NotDetermined){
            print("Not Authorised")
            locationManager.requestWhenInUseAuthorization()
        }
        
        loadPinAnnotations()
    }
    
    // MARK: Event handling
    
    func loadPinAnnotations() {
        
        let filePath = NSBundle.mainBundle().pathForResource("CampusMap", ofType: "plist")
        let properties = NSArray(contentsOfFile: filePath!)
        
        // Set MapView Region
        // -23.546954, -46.651796
        let centerCoordinate = CLLocationCoordinate2D(latitude: CLLocationDegrees(-23.546954), longitude: CLLocationDegrees(-46.651796))
        let region = MKCoordinateRegionMakeWithDistance(centerCoordinate, 600, 600)
        mapView.setRegion(region, animated: false)
        
        // Add Map Annotation
        for item in properties! {
            if let newPinData = item as? Dictionary<String,String>{
                let point = CGPointFromString(newPinData["location"]!)
                let coordinate = CLLocationCoordinate2D(latitude: CLLocationDegrees(point.x), longitude: CLLocationDegrees(point.y))
                
                let annotation = CampusMapAnnotation(name: newPinData["name"]!, buildName: newPinData["buildName"]!, number: newPinData["number"]!, coordinate: coordinate, color: newPinData["color"]!)
                mapView.addAnnotation(annotation)
            }
        }
    }
}

// MARK: - Map View delegate

extension CampusMapViewController: MKMapViewDelegate {
    func mapView(mapView: MKMapView, viewForAnnotation annotation: MKAnnotation) -> MKAnnotationView? {
        
        guard let annotation = annotation as? CampusMapAnnotation else {
            print(#function, "Problem with CampusMapAnnotation NIB")
            return nil
        }
        
        let view = self.mapView.dequeueReusableAnnotationViewWithIdentifier("CampusMap") ?? MKAnnotationView(annotation: annotation, reuseIdentifier: "CampusMap")
        
        let img =  UIImage(named: "pin")!.insertText(text: annotation.number, size: 16.0, offset: 0.2, color: annotation.color)
        
        view.image = img
        view.enabled = true
        view.canShowCallout = true
        view.centerOffset = CGPoint(x: 0, y: -img.size.height/2)
        
        return view
    }
    
    func mapView(mapView: MKMapView, didSelectAnnotationView view: MKAnnotationView) {
        if let origin = locValue {
            DirectionsAPI.sharedInstance.getPolyline(origin, destination: view.annotation!.coordinate) { (polylineEncoded, error) in
                var coordinates: [CLLocationCoordinate2D] = decodePolyline(polylineEncoded!)!
                coordinates.insert(origin, atIndex: 0)
                coordinates.append(view.annotation!.coordinate)
                let myPolyline = MKPolyline(coordinates: &coordinates, count: coordinates.count)
                self.mapView.removeOverlays(self.mapView.overlays)
                self.mapView.addOverlay(myPolyline)
                
            }
        }
    }

    func mapView(mapView: MKMapView, rendererForOverlay overlay: MKOverlay) -> MKOverlayRenderer {
        if overlay is MKPolyline {
            let lineView = MKPolylineRenderer(overlay: overlay)
            lineView.strokeColor = UIColor.redColor()
            lineView.lineWidth = 2;
            
            return lineView
        }
        return MKPolylineRenderer()
    }
    
    func mapView(mapView: MKMapView, didUpdateUserLocation userLocation: MKUserLocation) {
        locValue = userLocation.coordinate
    }

}
