//
//  SchedulesConfigurator.swift
//  MackTIA
//
//  Created by Luciano Moreira Turrini on 8/15/16.
//  Copyright (c) 2016 Mackenzie. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension SchedulesViewController: SchedulesPresenterOutput
{
  override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)
  {
    router.passDataToNextScene(segue)
  }
}

extension SchedulesInteractor: SchedulesViewControllerOutput
{
}

extension SchedulesPresenter: SchedulesInteractorOutput
{
}

class SchedulesConfigurator
{
  // MARK: Object lifecycle
  
  class var sharedInstance: SchedulesConfigurator
  {
    struct Static {
      static var instance: SchedulesConfigurator?
      static var token: dispatch_once_t = 0
    }
    
    dispatch_once(&Static.token) {
      Static.instance = SchedulesConfigurator()
    }
    
    return Static.instance!
  }
  
  // MARK: Configuration
  
  func configure(viewController: SchedulesViewController)
  {
    let router = SchedulesRouter()
    router.viewController = viewController
    
    let presenter = SchedulesPresenter()
    presenter.output = viewController
    
    let interactor = SchedulesInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
