//
//  SchedulesInteractor.swift
//  MackTIA
//
//  Created by Luciano Moreira Turrini on 8/15/16.
//  Copyright (c) 2016 Mackenzie. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol SchedulesInteractorInput
{
  func doSomething(request: SchedulesRequest)
}

protocol SchedulesInteractorOutput
{
  func presentSomething(response: SchedulesResponse)
}

class SchedulesInteractor: SchedulesInteractorInput
{
  var output: SchedulesInteractorOutput!
  var worker: SchedulesWorker!
  
  // MARK: Business logic
  
  func doSomething(request: SchedulesRequest)
  {
    // NOTE: Create some Worker to do the work
    
    worker = SchedulesWorker()
    worker.doSomeWork()
    
    // NOTE: Pass the result to the Presenter
    
    let response = SchedulesResponse()
    output.presentSomething(response)
  }
}
