//
//  SchedulesWorker.swift
//  MackTIA
//
//  Created by Luciano Moreira Turrini on 8/15/16.
//  Copyright (c) 2016 Mackenzie. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class SchedulesWorker
{
  // MARK: Business Logic
  
  func doSomeWork()
  {
    // NOTE: Do the work
  }
}
