//
//  SchedulesPresenter.swift
//  MackTIA
//
//  Created by Luciano Moreira Turrini on 8/15/16.
//  Copyright (c) 2016 Mackenzie. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol SchedulesPresenterInput
{
  func presentSomething(response: SchedulesResponse)
}

protocol SchedulesPresenterOutput: class
{
  func displaySomething(viewModel: SchedulesViewModel)
}

class SchedulesPresenter: SchedulesPresenterInput
{
  weak var output: SchedulesPresenterOutput!
  
  // MARK: Presentation logic
  
  func presentSomething(response: SchedulesResponse)
  {
    // NOTE: Format the response from the Interactor and pass the result back to the View Controller
    
    let viewModel = SchedulesViewModel()
    output.displaySomething(viewModel)
  }
}
